export * from './Square';
export * from './Rectangle';
export * from './Circle';
export * from './Triangle';
export * from './Oval';
export * from './Trapezoid';
export * from './Pentagon';
export * from './Hexagon';
export * from './Octagon';
